print( "my name is Lubna")
print( "my name is Lubna")
print( "my name is Lubna")
print( "my name is Lubna")
print( "my name is Lubna")
print( "my name is Lubna")
print( "my name is Lubna")
print( "my name is Lubna")
print( "my name is Lubna")
print( "my name is Lubna")
print( "my name is Lubna")print( "my name is Lubna")